apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: cbp-deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
      url:
        type: string
        required: false
      digest:
        type: string
        required: false
jobs:
  deploy:
    # environment: "${{ inputs.environment }}"
    steps:
      - name: Inform system that an artifact version was deployed
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{ inputs.artifactVersion }}"
          url: "docker.io/SampleApp/${{ inputs.artifactName }}:${{ inputs.artifactVersion }}"
          target-environment: "${{ inputs.environment }}"
          
