apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: cbp-deploy
on:
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
      url:
        type: string
        required: false
      digest:
        type: string
        required: false
      artifactId:
        type: string
        required: false
jobs:
  deploy:
    # environment: "${{ inputs.environment }}"
    steps:
      - name: Inform system that an artifact version was deployed
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: "${{ inputs.artifactId }}"
          target-environment: "${{ inputs.environment }}"
          
